# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DD.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow, itemName):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(810, 541)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 6, 0, 1, 1)
        self.item_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.item_4.setObjectName(itemName)
        self.gridLayout_7.addWidget(self.item_4, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 11, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 8, 0, 1, 1)
        self.item_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.item_1.setObjectName("item_1")
        self.gridLayout_7.addWidget(self.item_1, 1, 0, 1, 1)
        self.item_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.item_3.setObjectName("item_3")
        self.gridLayout_7.addWidget(self.item_3, 5, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 4, 0, 1, 1)
        self.item_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.item_2.setObjectName("item_2")
        self.gridLayout_7.addWidget(self.item_2, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 2, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 2, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_2, 10, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_7.addLayout(self.gridLayout_5, 9, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 13, 0, 1, 1)
        self.item_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.item_7.setObjectName("item_7")
        self.gridLayout_4.addWidget(self.item_7, 7, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 2, 0, 1, 1)
        self.item_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.item_5.setObjectName("item_5")
        self.gridLayout_4.addWidget(self.item_5, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 6, 0, 1, 1)
        self.item_Label6 = QtWidgets.QLabel(self.centralwidget)
        self.item_Label6.setObjectName("item_Label6")
        self.gridLayout_4.addWidget(self.item_Label6, 4, 0, 1, 1)
        self.textItem_8 = QtWidgets.QLabel(self.centralwidget)
        self.textItem_8.setObjectName("textItem_8")
        self.gridLayout_4.addWidget(self.textItem_8, 8, 0, 1, 1)
        self.item_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.item_8.setObjectName("item_8")
        self.gridLayout_4.addWidget(self.item_8, 9, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 10, 0, 1, 1)
        self.item_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.item_9.setObjectName("item_9")
        self.gridLayout_4.addWidget(self.item_9, 5, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 810, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_11.setText(_translate("MainWindow", "Item4"))
        self.label.setText(_translate("MainWindow", "Item1"))
        self.label_7.setText(_translate("MainWindow", "Item 3"))
        self.label_3.setText(_translate("MainWindow", "Item2"))
        self.label_6.setText(_translate("MainWindow", "Quantity"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.label_4.setText(_translate("MainWindow", "Record Inventory"))
        self.label_5.setText(_translate("MainWindow", "Item Number:"))
        self.label_2.setText(_translate("MainWindow", "Item5"))
        self.label_9.setText(_translate("MainWindow", "Item7"))
        self.item_Label6.setText(_translate("MainWindow", "Item6"))
        self.textItem_8.setText(_translate("MainWindow", "Item8"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

